apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:elasticloadbalancing:ap-northeast-2:621211789789:loadbalancer/net/a1ae4148612c7402ca1db1f615850ca7/b3b5772db097bf04
spec:
  selector:
    app: frontend-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  type: LoadBalancer




